// lib/domains.ts

export interface DomainCategory {
  id: string;
  name: string;
  icon?: string;
  subcategories: string[];
}

export const RESEARCH_DOMAINS: DomainCategory[] = [
  {
    id: 'cs_ai',
    name: 'Computer Science & AI',
    subcategories: [
      'Artificial Intelligence',
      'Machine Learning',
      'Deep Learning',
      'Generative AI',
      'Large Language Models / LLMs',
      'Natural Language Processing',
      'Computer Vision',
      'Robotics',
      'Reinforcement Learning',
      'Explainable AI',
      'Responsible AI',
      'AI Agents',
      'Multimodal AI',
      'Speech Recognition',
      'Information Retrieval',
      'Knowledge Graphs',
      'Data Mining',
      'Data Science',
      'Big Data',
      'Human-Computer Interaction',
      'Software Engineering',
      'Distributed Systems',
      'Cloud Computing',
      'Edge Computing',
      'Internet of Things',
      'Cybersecurity',
      'Network Security',
      'Cryptography',
      'Blockchain',
      'Computer Networks',
      'Operating Systems',
      'Computer Architecture',
      'Embedded Systems',
      'Database Systems',
      'Algorithms & Theory',
      'Web Technologies',
      'Mobile Computing',
      'Computer Graphics',
      'AR/VR/XR',
      'Bioinformatics',
      'Computational Science',
    ],
  },
  {
    id: 'engineering',
    name: 'Engineering',
    subcategories: [
      'Electrical Engineering',
      'Electronics Engineering',
      'Computer Engineering',
      'Mechanical Engineering',
      'Civil Engineering',
      'Chemical Engineering',
      'Industrial Engineering',
      'Mechatronics Engineering',
      'Biomedical Engineering',
      'Environmental Engineering',
      'Aerospace Engineering',
      'Automotive Engineering',
      'Materials Engineering',
      'Telecommunications Engineering',
      'Control Systems',
      'Signal Processing',
      'Power Systems',
      'Renewable Energy Engineering',
      'Structural Engineering',
      'Transportation Engineering',
      'Water Resources Engineering',
      'Geotechnical Engineering',
      'Manufacturing Engineering',
      'Robotics Engineering',
    ],
  },
  {
    id: 'energy_env',
    name: 'Energy & Environment',
    subcategories: [
      'Renewable Energy',
      'Solar Energy',
      'Wind Energy',
      'Energy Storage',
      'Battery Technology',
      'Smart Grids',
      'Sustainable Energy',
      'Environmental Science',
      'Climate Science',
      'Climate Change',
      'Carbon Capture',
      'Sustainability',
      'Water Management',
      'Waste Management',
      'Environmental Engineering',
      'Green Technology',
    ],
  },
  {
    id: 'biomedical',
    name: 'Biomedical & Health',
    subcategories: [
      'Biomedical Sciences',
      'Biomedical Engineering',
      'Bioinformatics',
      'Computational Biology',
      'Biotechnology',
      'Genetics',
      'Genomics',
      'Neuroscience',
      'Medical Imaging',
      'Digital Health',
      'Health Informatics',
      'Public Health',
      'Pharmaceutical Sciences',
      'Drug Discovery',
      'Medical AI',
      'Cancer Research',
      'Immunology',
      'Microbiology',
    ],
  },
  {
    id: 'natural_sci',
    name: 'Natural Sciences',
    subcategories: [
      'Physics',
      'Applied Physics',
      'Astrophysics',
      'Quantum Physics',
      'Quantum Computing',
      'Chemistry',
      'Materials Science',
      'Mathematics',
      'Applied Mathematics',
      'Statistics',
      'Earth Sciences',
      'Geology',
      'Atmospheric Science',
      'Oceanography',
    ],
  },
  {
    id: 'business_econ',
    name: 'Business, Economics & Management',
    subcategories: [
      'Business Analytics',
      'Finance',
      'Financial Technology / FinTech',
      'Economics',
      'Econometrics',
      'Marketing',
      'Digital Marketing',
      'Entrepreneurship',
      'Management',
      'Operations Management',
      'Supply Chain Management',
      'Human Resources',
      'Organizational Behavior',
      'Accounting',
      'Information Systems',
    ],
  },
  {
    id: 'social_sci',
    name: 'Social Sciences',
    subcategories: [
      'Psychology',
      'Cognitive Science',
      'Sociology',
      'Political Science',
      'International Relations',
      'Education',
      'Communication',
      'Media Studies',
      'Anthropology',
      'Behavioral Science',
      'Linguistics',
    ],
  },
  {
    id: 'design_humanities',
    name: 'Design & Humanities',
    subcategories: [
      'Human-Computer Interaction',
      'UX/UI',
      'Interaction Design',
      'Industrial Design',
      'Architecture',
      'Urban Planning',
      'Digital Humanities',
      'Linguistics',
      'Literature',
      'History',
      'Philosophy',
    ],
  },
  {
    id: 'agri_food',
    name: 'Agriculture & Food',
    subcategories: [
      'Agricultural Engineering',
      'Agricultural Sciences',
      'Precision Agriculture',
      'Smart Agriculture',
      'Food Science',
      'Food Technology',
      'Plant Science',
      'Animal Science',
      'Soil Science',
      'Agricultural Biotechnology',
    ],
  },
  {
    id: 'law_policy',
    name: 'Law & Policy',
    subcategories: [
      'Technology Law',
      'Cyber Law',
      'Intellectual Property',
      'International Law',
      'Environmental Law',
      'Public Policy',
      'Technology Policy',
      'AI Governance',
    ],
  },
];

export const INTENT_KEYWORDS = [
  'Research Assistantship',
  'PhD Research',
  'MS Research',
  'Thesis Supervision',
  'Graduate Research',
  'Lab Opportunities',
  'Fully Funded PhD',
  'Research Internship',
  'Professor Outreach',
  'International Student Research',
  'Scholarship Opportunities',
  'Funding Opportunities',
];
